/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : KBI0.c
**     Project     : Arpie2
**     Processor   : MKE02Z64VLC4
**     Component   : Init_KBI
**     Version     : Component 01.000, Driver 01.00, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2017-02-10, 23:07, # CodeGen: 56
**     Abstract    :
**          This file implements the KBI (KBI0) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : KBI0
**          Device                                         : KBI0
**          Settings                                       : 
**            Clock gate                                   : Do not initialize
**            Detection mode                               : Edges only
**            Pin sensitivity                              : 
**              Input pin 0                                : Falling edge or low level
**              Input pin 1                                : Falling edge or low level
**              Input pin 2                                : Falling edge or low level
**              Input pin 3                                : Falling edge or low level
**              Input pin 4                                : Falling edge or low level
**              Input pin 5                                : Falling edge or low level
**              Input pin 6                                : Falling edge or low level
**              Input pin 7                                : Falling edge or low level
**          Pins/Signals                                   : 
**            Input pin 0                                  : Disabled
**            Input pin 1                                  : Disabled
**            Input pin 2                                  : Disabled
**            Input pin 3                                  : Disabled
**            Input pin 4                                  : Disabled
**            Input pin 5                                  : Disabled
**            Input pin 6                                  : Enabled
**              Input pin 6                                : PTB2/KBI0_P6/SPI0_SCK/FTM0_CH0/ADC0_SE6
**              Input pin 6 signal                         : 
**            Input pin 7                                  : Enabled
**              Input pin 7                                : PTB3/KBI0_P7/SPI0_MOSI/FTM0_CH1/ADC0_SE7
**              Input pin 7 signal                         : 
**          Interrupts                                     : 
**            Interrupt                                    : INT_KBI0
**            Interrupt request                            : Enabled
**            Interrupt priority                           : 0 (Highest)
**            ISR name                                     : INT_Encoder
**            KBI interrupt                                : Enabled
**          Initialization                                 : 
**            Call Init method                             : no
**     Contents    :
**         Init - void KBI0_Init(void);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file KBI0.c
** @version 01.00
** @brief
**          This file implements the KBI (KBI0) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup KBI0_module KBI0 module documentation
**  @{
*/         

/* MODULE KBI0. */

#include "KBI0.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  KBI0_Init (component Init_KBI)
**     Description :
**         This method initializes registers of the KBI module
**         according to the Peripheral Initialization settings.
**         Call this method in user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void KBI0_Init(void)
{
  /* KBI0_SC: ??=0,??=0,??=0,??=0,KBF=0,KBACK=0,KBIE=0,KBMOD=0 */
  KBI0_SC = 0x00U;
  /* KBI0_ES: KBEDG=0 */
  KBI0_ES = KBI_ES_KBEDG(0x00);
  /* KBI0_PE: KBIPE=0xC0 */
  KBI0_PE = KBI_PE_KBIPE(0xC0);
  /* KBI0_SC: KBACK=1 */
  KBI0_SC |= KBI_SC_KBACK_MASK;
  /* KBI0_SC: KBIE=1 */
  KBI0_SC |= KBI_SC_KBIE_MASK;
}

/*
** ###################################################################
**
**  The interrupt service routine(s) must be implemented
**  by user in one of the following user modules.
**
**  If the "Generate ISR" option is enabled, Processor Expert generates
**  ISR templates in the CPU event module.
**
**  User modules:
**      main.c
**      Events.c
**
** ###################################################################
PE_ISR(INT_Encoder)
{
// NOTE: The routine should include actions to clear the appropriate
//       interrupt flags.
//
}
*/


/* END KBI0. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
